title = "geobites gitleaks config"

[allowlist]
  description = "Ignore encrypted creds and Devise template initializer"
  paths = [
    '''^config/credentials\.yml\.enc$''',
    '''^config/initializers/devise\.rb$'''
  ]
